Repository naomis-novas/homepage, pull requests merged in 2021-09, with the labels that each got.

#32 Welcome box height
  public/index.css
Labels: 🕹 aspect: interface

#34 Updated the card styling
  public/modcard.css
Labels: 💻 aspect: code, 🕹 aspect: interface

#35 feat: use placeholder
  index.html
  public/data/_template.json
  public/utilities.css
Labels: ⭐ goal: addition, 🕹 aspect: interface
